"""migracao concluida

Revision ID: 27244f1fc5ca
Revises: 
Create Date: 2025-07-10 09:33:41.406235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27244f1fc5ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('horario', sa.String(length=50), nullable=False),
    sa.Column('carga_horaria', sa.String(length=50), nullable=False),
    sa.Column('local', sa.String(length=120), nullable=False),
    sa.Column('vagas_disponiveis', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.Enum('ABERTO', 'CANCELADO', 'REALIZADO', name='situacaocurso'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('email_confirmado', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('link_inscricao', sa.String(length=255), nullable=False),
    sa.Column('vagas_disponiveis', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMADA', 'CANCELADA', 'REALIZADA', name='statusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.String(length=50), nullable=False),
    sa.Column('duracao', sa.String(length=20), nullable=False),
    sa.Column('local', sa.String(length=100), nullable=False),
    sa.Column('vagas_disponiveis', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'CANCELADO', 'REALIZADO', name='situacaocurso'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso_inscricao',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'curso_id')
    )
    op.create_table('estudante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso', sa.String(length=100), nullable=False),
    sa.Column('numero_matricula', sa.String(length=50), nullable=False),
    sa.Column('data_entrada_ufes', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siape', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita_inscricao',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visita.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'visita_id')
    )
    op.create_table('workshop_inscricao',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workshop_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshop_inscricao')
    op.drop_table('visita_inscricao')
    op.drop_table('professor')
    op.drop_table('estudante')
    op.drop_table('curso_inscricao')
    op.drop_table('workshop')
    op.drop_table('visita')
    op.drop_table('user')
    op.drop_table('curso')
    # ### end Alembic commands ###
