"""adicao apresentacoes

Revision ID: f9eba4bac7d7
Revises: 27244f1fc5ca
Create Date: 2025-07-29 08:25:48.363290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9eba4bac7d7'
down_revision = '27244f1fc5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apresentacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('link_inscricao', sa.String(length=255), nullable=False),
    sa.Column('vagas_disponiveis', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMADA', 'CANCELADA', 'REALIZADA', name='statusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apresentacao_inscricao',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('apresentacao_id', sa.Integer(), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['apresentacao_id'], ['apresentacao.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'apresentacao_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apresentacao_inscricao')
    op.drop_table('apresentacao')
    # ### end Alembic commands ###
